import { Inter } from 'next/font/google'
import './globals.css'
import { ContextCarrito } from '@/context/ContextCarrito'
import Carrito from '@/components/Carrito/Carrito'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {


  return (
    <html lang="en">
    <ContextCarrito>
      <body className={inter.className}>
        <nav>
          <h1>Frutas y verduras UP</h1>
          <Carrito/>
        </nav>
        {children}
      </body>
    </ContextCarrito>
    </html>
  )
}
